# [Day 14](https://github.com/Muhtoyyib/30-DAY-JAVASCRIPT/blob/main/Day14/day14.md)

Welcome to Day 14 of our 30-Day JavaScript Challenge! 

Today, we're diving into **Error Handling**.

**Error handling** in JavaScript involves managing unexpected situations to prevent script termination. It utilizes constructs like `try`, `catch`, `finally`, and the `throw` statement. The `try` block encloses code that might throw an error, while `catch` handles specific errors gracefully. The `finally` block executes regardless of the outcome. Exceptional situations trigger the `throw` statement, allowing custom error messages. Robust error handling enhances code reliability, aiding developers in identifying, understanding, and addressing issues, ultimately ensuring more resilient and user-friendly applications.

Before you proceed to the [solutions](solutions-day14/) folder, make sure to review the essential concepts and exercises in the <a href="https://github.com/Asabeneh/30-Days-Of-JavaScript/blob/master/14_Day_Error_handling/13_day_console_object_methods.md" target="_blank"> Introduction document</a>.

Let's code, create, and conquer together 👨🏻‍💻🚀💪🏻!

[<< Day 13](https://github.com/Muhtoyyib/30-DAY-JAVASCRIPT/blob/main/Day13/day13.md) | [Day 15 >>](https://github.com/Muhtoyyib/30-DAY-JAVASCRIPT/blob/main/Day15/day15.md)